# This file was generated by GoReleaser. DO NOT EDIT.
cask "adbt" do
  name "adbt"
  desc "A modern, keyboard-driven Android Debug Bridge TUI."
  homepage "https://github.com/SakshhamTheCoder/adbt"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adbt"

  on_macos do
    on_intel do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Darwin_x86_64.tar.gz"
      sha256 "37c60f0826cd94a86677b5dd92c1210fd0aba61bb6d4a9ae60614628b0408b9b"
    end
    on_arm do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Darwin_arm64.tar.gz"
      sha256 "b4619d240476fca37f1d668a1325e4118e34ec1c1aa84081b3ca21929cd892be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Linux_x86_64.tar.gz"
      sha256 "052d21ab0a9870684121c07705cfc965b4d5c057a56b8fc301dee71ab5a95da4"
    end
    on_arm do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Linux_arm64.tar.gz"
      sha256 "acc0f0ae17a55874e7df456720357dd18b519ae90e7b779615d9598b9b053d53"
    end
  end

  # No zap stanza required
end
