# This file was generated by GoReleaser. DO NOT EDIT.
cask "adbt" do
  name "adbt"
  desc "A modern, keyboard-driven Android Debug Bridge TUI."
  homepage "https://github.com/SakshhamTheCoder/adbt"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adbt"

  on_macos do
    on_intel do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Darwin_x86_64.tar.gz"
      sha256 "9fafebdc4abb032a6947100d5e8627cb3eda02e3439f04eafe780519f8558ffc"
    end
    on_arm do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Darwin_arm64.tar.gz"
      sha256 "f3a0628cdbf30e6f0a9aa56fa8a311bf4b0c0d918e1e2633d783355bad0e863c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Linux_x86_64.tar.gz"
      sha256 "5377eaed2e0c8ce18227e40b1326eaf1a0283364fe9599a8d708653815bc6cb7"
    end
    on_arm do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Linux_arm64.tar.gz"
      sha256 "b2a5ec4dd9c22f22049d752c4825cee3e255b2c01962a9cff8d0c7cb546edd9b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adbt"]
    end
  end

  # No zap stanza required
end
