# This file was generated by GoReleaser. DO NOT EDIT.
cask "adbt" do
  name "adbt"
  desc "A modern, keyboard-driven Android Debug Bridge TUI."
  homepage "https://github.com/SakshhamTheCoder/adbt"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adbt"

  on_macos do
    on_intel do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Darwin_x86_64.tar.gz"
      sha256 "93bd3efefd0eb6d21903929d7cb04bc2f26eb3c8c452b72cec07f1568218e1c9"
    end
    on_arm do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Darwin_arm64.tar.gz"
      sha256 "a9ed52de35570e2965230e28599f997260f2020e90f0621ba99b5f948176498b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Linux_x86_64.tar.gz"
      sha256 "1a5fb88becf30525c6109d70e21072cf87c93b92aea8cf93b9644baf4b76844b"
    end
    on_arm do
      url "https://github.com/SakshhamTheCoder/adbt/releases/download/v#{version}/adbt_Linux_arm64.tar.gz"
      sha256 "ec8ccb8089019328e563028fbdb103e5ed0a44d7b0ba32fa30f17fb007fa0434"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adbt"]
    end
  end

  # No zap stanza required
end
